apiVersion: v1
kind: Service
metadata:
  name: barlevelservice
  namespace: default
  labels:
    app: barlevelservice
spec:
  selector:
    app: barlevelservice
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
